let agShard = "aghanims-shard-bf9def7dc51a9f3191c8303418a5ffc97cab23cbed5a9b1369254b75e8753885.jpg";
let PT = "power-treads.jpg";
let wand = "magic-wand.jpg";
let meka = "mekansm.jpg";
let blink = "blink-dagger.jpg";
let sashakaya = "kaya-and-sange.jpg";
let dust = "dust-of-appearance.jpg";
let BF = "battle-fury.jpg";
let butter = "butterfly.jpg";
let linka = "linkens-sphere.jpg";
let satanic = "satanic.jpg";
let blyadorn = "bloodthorn.jpg";
let manta = "manta-style.jpg";
let urna = "urn-of-shadows.jpg";
let phases = "phase-boots.jpg";
let lotar = "shadow-blade.jpg";
let crystal = "crystalys.jpg";
let aganim = "aghanims-scepter.jpg";
let windlace = "wind-lace.jpg";
let travel2 = "boots-of-travel-level-2.jpg";
let refresher = "refresher-orb.jpg";
let nolifer = "nullifier.jpg";
let BKB = "black-king-bar.jpg";

export let matchData = [
  {
    heroImg: "heroimages/void-spirit.jpg",
    herolvl: 25,
    roleImg: "roleimages/carry.svg",
    laneImg: "roleimages/mid.svg",
    nickName: "Anonymous",
    laneOut: "Middle Drew",
    K: 3,
    D: 9,
    A: 10,
    NET: "15.5k",
    LH: 232,
    DN: 3,
    GPM: 395,
    XPM: 694,
    DMG: "36.3k",
    HEAL: 110,
    BLD: "-",
    wards: '<span class="ward">2</span> / <span class="sentry">1</span>',
    isBuffs: "Buffs:",
    items: {
      buffs: `<img class="match-info__buffs-image" src="itemimages/${agShard}">`,

      initems:
        '<div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/bottle.jpg"><span class="match-info__itemmin">1m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/magic-wand.jpg"><span class="match-info__itemmin">4m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/euls-scepter-of-divinity.jpg"><span class="match-info__itemmin">12m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/aghanims-scepter.jpg"><span class="match-info__itemmin">34m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/kaya.jpg"><span class="match-info__itemmin">42m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/boots-of-travel.jpg"><span class="match-info__itemmin"></span></div>',
      neutralitem: "itemimages/stormcrafter.jpg",
      bagitems: "",
    },
  },

  {
    heroImg: "heroimages/lich.jpg",
    herolvl: 16,
    roleImg: "roleimages/support.svg",
    laneImg: "roleimages/save.svg",
    nickName: "Anonymous",
    laneOut: "Bottom (Safe) Lost",
    K: 1,
    D: 19,
    A: 8,
    NET: "7.1k",
    LH: 31,
    DN: 1,
    GPM: 268,
    XPM: 280,
    DMG: "16.7k",
    HEAL: 716,
    BLD: "-",
    wards: '<span class="ward">18</span>/<span class="sentry">39</span>',
    isBuffs: "Buffs:",
    items: {
      buffs: '<img class="match-info__buffs-image" src="itemimages/tome-of-knowledge.jpg">',

      initems:
        '<div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/sentry-ward.jpg"><span class="match-info__itemmin">0m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/dust-of-appearance.jpg"><span class="match-info__itemmin">7m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/tranquil-boots.jpg"><span class="match-info__itemmin">17m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/magic-wand.jpg"><span class="match-info__itemmin">22m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/glimmer-cape.jpg"><span class="match-info__itemmin">26m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/force-staff.jpg"><span class="match-info__itemmin">36m</span></div>',
      neutralitem: "itemimages/telescope.jpg",
      bagitems:
        '<div class="match-info__initems-wrapper"><img class="match-info__bagitem-image" src="itemimages/dust-of-appearance.jpg"><span class="match-info__itemmin">2m</span></div>',
    },
  },

  {
    heroImg: "heroimages/necrophos.jpg",
    herolvl: 21,
    roleImg: "roleimages/carry.svg",
    laneImg: "roleimages/offlane.svg",
    nickName: '<a href="#" class="radiant--highlight">Alizee</a>',
    laneOut: "Top (Off) Lost",
    K: 6,
    D: 16,
    A: 7,
    NET: "14.8k",
    LH: 163,
    DN: 4,
    GPM: 378,
    XPM: 429,
    DMG: "20.4k",
    HEAL: "5.8k",
    BLD: "375",
    wards: '<span class="ward">-</span>/<span class="sentry">1</span>',
    isBuffs: "Buffs:",
    items: {
      buffs: '<img class="match-info__buffs-image" src="itemimages/aghanims-shard-bf9def7dc51a9f3191c8303418a5ffc97cab23cbed5a9b1369254b75e8753885.jpg">',

      initems: `<div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${wand}"><span class="match-info__itemmin">4m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${PT}"><span class="match-info__itemmin">7m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${meka}"><span class="match-info__itemmin">15m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${blink}"><span class="match-info__itemmin">22m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${sashakaya}"><span class="match-info__itemmin">26m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${dust}"><span class="match-info__itemmin">38m</span></div>`,
      neutralitem: "itemimages/ceremonial-robe.jpg",
      bagitems:
        '<div class="match-info__initems-wrapper"><img class="match-info__bagitem-image" src="itemimages/wind-lace.jpg"><span class="match-info__itemmin">2m</span></div>',
    },
  },

  {
    heroImg: "heroimages/anti-mage.jpg",
    herolvl: 30,
    roleImg: "roleimages/carry.svg",
    laneImg: "roleimages/save.svg",
    nickName: '<span><img class="check-img" src="roleimages/check-solid.svg"></span><a href="#" class="radiant--highlight">TSpirit.Yatoro</a>',
    laneOut: "Bottom (Safe) Lost",
    K: 11,
    D: 6,
    A: 7,
    NET: "31.4k",
    LH: 445,
    DN: 8,
    GPM: 726,
    XPM: 806,
    DMG: "52.4k",
    HEAL: "-",
    BLD: "10.7k",
    wards: '<span class="ward">-</span>/<span class="sentry">-</span>',
    isBuffs: "Buffs:",
    items: {
      buffs: '<img class="match-info__buffs-image" src="itemimages/tome-of-knowledge.jpg">',

      initems: `<div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${BF}"><span class="match-info__itemmin">17m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${manta}"><span class="match-info__itemmin">23m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${blyadorn}"><span class="match-info__itemmin">15m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${satanic}"><span class="match-info__itemmin">39m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${linka}"><span class="match-info__itemmin">42m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${butter}"><span class="match-info__itemmin">38m</span></div>`,
      neutralitem: "itemimages/ninja-gear.jpg",
      bagitems: "",
    },
  },

  {
    heroImg: "heroimages/spirit-breaker.jpg",
    herolvl: 21,
    roleImg: "roleimages/carry.svg",
    laneImg: "roleimages/offlane.svg",
    nickName: "Anonymous",
    laneOut: "Top (Off) Lost",
    K: 2,
    D: 23,
    A: 10,
    NET: "13.5k",
    LH: 209,
    DN: 1,
    GPM: 384,
    XPM: 426,
    DMG: "19.7k",
    HEAL: "-",
    BLD: "60",
    wards: '<span class="ward">2</span>/<span class="sentry">2</span>',
    isBuffs: "Buffs:",
    items: {
      buffs: `<img class="match-info__buffs-image" src="itemimages/${agShard}">`,

      initems: `<div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${urna}"><span class="match-info__itemmin">6m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${phases}"><span class="match-info__itemmin">11m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${lotar}"><span class="match-info__itemmin">15m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${aganim}"><span class="match-info__itemmin">39m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${crystal}"><span class="match-info__itemmin">42m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${windlace}"><span class="match-info__itemmin">38m</span></div>`,
      neutralitem: "itemimages/trickster-cloak.jpg",
      bagitems:
        '<div class="match-info__initems-wrapper"><img class="match-info__bagitem-image" src="itemimages/clarity.jpg"><span class="match-info__itemmin">2m</span></div><div class="match-info__initems-wrapper"><img class="match-info__bagitem-image" src="itemimages/dust-of-appearance.jpg"><span class="match-info__itemmin">2m</span></div>',
    },
  },
];

export let matchData2 = [
  {
    heroImg: "heroimages/phantom-assassin.jpg",
    herolvl: 30,
    roleImg: "roleimages/carry.svg",
    laneImg: "roleimages/save.svg",
    nickName: "Anonymous",
    laneOut: "Top (Safe) Wom",
    K: 24,
    D: 1,
    A: 26,
    NET: "42.0k",
    LH: 599,
    DN: 28,
    GPM: 943,
    XPM: 846,
    DMG: "68.3k",
    HEAL: 110,
    BLD: "14.1k",
    wards: '<span class="ward">-</span> / <span class="sentry">-</span>',
    isBuffs: "Buffs:",
    items: {
      buffs: `<img class="match-info__buffs-image" src="itemimages/${agShard}">`,

      initems: `<div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${BF}"><span class="match-info__itemmin">6m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${BKB}"><span class="match-info__itemmin">11m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${nolifer}"><span class="match-info__itemmin">15m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${linka}"><span class="match-info__itemmin">39m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${refresher}"><span class="match-info__itemmin">42m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${travel2}"><span class="match-info__itemmin">38m</span></div>`,
      neutralitem: "itemimages/the-leveller.jpg",
      bagitems: "",
    },
  },

  {
    heroImg: "heroimages/storm-spirit.jpg",
    herolvl: 16,
    roleImg: "roleimages/support.svg",
    laneImg: "roleimages/save.svg",
    nickName: "Anonymous",
    laneOut: "Bottom (Safe) Lost",
    K: 1,
    D: 19,
    A: 8,
    NET: "7.1k",
    LH: 31,
    DN: 1,
    GPM: 268,
    XPM: 280,
    DMG: "16.7k",
    HEAL: 716,
    BLD: "-",
    wards: '<span class="ward">18</span>/<span class="sentry">39</span>',
    isBuffs: "Buffs:",
    items: {
      buffs: '<img class="match-info__buffs-image" src="itemimages/tome-of-knowledge.jpg">',

      initems:
        '<div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/sentry-ward.jpg"><span class="match-info__itemmin">0m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/dust-of-appearance.jpg"><span class="match-info__itemmin">7m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/tranquil-boots.jpg"><span class="match-info__itemmin">17m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/magic-wand.jpg"><span class="match-info__itemmin">22m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/glimmer-cape.jpg"><span class="match-info__itemmin">26m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/force-staff.jpg"><span class="match-info__itemmin">36m</span></div>',
      neutralitem: "itemimages/telescope.jpg",
      bagitems: "",
    },
  },

  {
    heroImg: "heroimages/undying.jpg",
    herolvl: 21,
    roleImg: "roleimages/carry.svg",
    laneImg: "roleimages/offlane.svg",
    nickName: '<a href="#" class="radiant--highlight">Alizee</a>',
    laneOut: "Top (Off) Lost",
    K: 6,
    D: 16,
    A: 7,
    NET: "14.8k",
    LH: 163,
    DN: 4,
    GPM: 378,
    XPM: 429,
    DMG: "20.4k",
    HEAL: "5.8k",
    BLD: "375",
    wards: '<span class="ward">19</span>/<span class="sentry">39</span>',
    isBuffs: "Buffs:",
    items: {
      buffs: '<img class="match-info__buffs-image" src="itemimages/aghanims-shard-bf9def7dc51a9f3191c8303418a5ffc97cab23cbed5a9b1369254b75e8753885.jpg">',

      initems: `<div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${wand}"><span class="match-info__itemmin">4m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${PT}"><span class="match-info__itemmin">7m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${meka}"><span class="match-info__itemmin">15m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${blink}"><span class="match-info__itemmin">22m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${sashakaya}"><span class="match-info__itemmin">26m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${dust}"><span class="match-info__itemmin">38m</span></div>`,
      neutralitem: "itemimages/ceremonial-robe.jpg",
      bagitems:
        '<div class="match-info__initems-wrapper"><img class="match-info__bagitem-image" src="itemimages/wind-lace.jpg"><span class="match-info__itemmin">2m</span></div>',
    },
  },

  {
    heroImg: "heroimages/rubick.jpg",
    herolvl: 30,
    roleImg: "roleimages/carry.svg",
    laneImg: "roleimages/save.svg",
    nickName: '<span><img class="check-img" src="roleimages/check-solid.svg"></span><a href="#" class="radiant--highlight">TSpirit.Yatoro</a>',
    laneOut: "Bottom (Safe) Lost",
    K: 11,
    D: 6,
    A: 7,
    NET: "31.4k",
    LH: 445,
    DN: 8,
    GPM: 726,
    XPM: 806,
    DMG: "52.4k",
    HEAL: "-",
    BLD: "10.7k",
    wards: '<span class="ward">-</span>/<span class="sentry">-</span>',
    isBuffs: "Buffs:",
    items: {
      buffs: '<img class="match-info__buffs-image" src="itemimages/tome-of-knowledge.jpg">',

      initems: `<div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${BF}"><span class="match-info__itemmin">17m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${manta}"><span class="match-info__itemmin">23m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${blyadorn}"><span class="match-info__itemmin">15m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${satanic}"><span class="match-info__itemmin">39m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${linka}"><span class="match-info__itemmin">42m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${butter}"><span class="match-info__itemmin">38m</span></div>`,
      neutralitem: "itemimages/ninja-gear.jpg",
      bagitems: "",
    },
  },

  {
    heroImg: "heroimages/marci.jpg",
    herolvl: 21,
    roleImg: "roleimages/carry.svg",
    laneImg: "roleimages/offlane.svg",
    nickName: "Anonymous",
    laneOut: "Top (Off) Lost",
    K: 2,
    D: 23,
    A: 10,
    NET: "13.5k",
    LH: 209,
    DN: 1,
    GPM: 384,
    XPM: 426,
    DMG: "19.7k",
    HEAL: "-",
    BLD: "60",
    wards: '<span class="ward">2</span>/<span class="sentry">2</span>',
    isBuffs: "Buffs:",
    items: {
      buffs: `<img class="match-info__buffs-image" src="itemimages/${agShard}">`,

      initems: `<div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${urna}"><span class="match-info__itemmin">6m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${phases}"><span class="match-info__itemmin">11m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${lotar}"><span class="match-info__itemmin">15m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${aganim}"><span class="match-info__itemmin">39m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${crystal}"><span class="match-info__itemmin">42m</span></div><div class="match-info__initems-wrapper"><img class="match-info__initems-image" src="itemimages/${windlace}"><span class="match-info__itemmin">38m</span></div>`,
      neutralitem: "itemimages/trickster-cloak.jpg",
      bagitems:
        '<div class="match-info__initems-wrapper"><img class="match-info__bagitem-image" src="itemimages/clarity.jpg"><span class="match-info__itemmin">2m</span></div><div class="match-info__initems-wrapper"><img class="match-info__bagitem-image" src="itemimages/dust-of-appearance.jpg"><span class="match-info__itemmin">2m</span></div>',
    },
  },
];


export let hintData = [
  {
    name: "Void Spirit",
    heroImage: "heroimages/void-spirit.jpg",
    heroType: "Intellegence Hero",
    typeImage: "roleimages/intell.svg",
    popularPlace: "46th",
    popularPercent: "49.54%",
    stengthGain: "22+2.6",
    agilityGain: "19+2.2",
    itellegenceGain: "24+3.1",
    speed: 295,
    armor: 1.66,
    roles: "Melee, Carry, Disabler, Escape, Nuke",
  },
  {
    name: "Lich",
    heroImage: "heroimages/lich.jpg",
    heroType: "Intellegence Hero",
    typeImage: "roleimages/intell.svg",
    popularPlace: "58th",
    popularPercent: "50%",
    stengthGain: "20+2.1",
    agilityGain: "15+2.0",
    itellegenceGain: "24+4.1",
    speed: 295,
    armor: 1.1,
    roles: "Ranged, Nuke, Support",
  },

  {
    name: "Necrophos",
    heroImage: "heroimages/necrophos.jpg",
    heroType: "Intellegence Hero",
    typeImage: "roleimages/intell.svg",
    popularPlace: "48th",
    popularPercent: "52.23%",
    stengthGain: "18+2.3",
    agilityGain: "12+1.3",
    itellegenceGain: "21+2.7",
    speed: 280,
    armor: 2.68,
    roles: "Ranged, Carry, Disable, Durable, Nuke",
  },
  {
    name: "Anti-Mage",
    heroImage: "heroimages/anti-mage.jpg",
    heroType: "Agility Hero",
    typeImage: "roleimages/agill.svg",
    popularPlace: "17th",
    popularPercent: "51.67%",
    stengthGain: "23+1.6",
    agilityGain: "24+2.8",
    itellegenceGain: "12+1.8",
    speed: 310,
    armor: 3.36,
    roles: "Melee, Carry, Escape, Nuke",
  },
  {
    name: "Spirit Breaker",
    heroImage: "heroimages/spirit-breaker.jpg",
    heroType: "Strength Hero",
    typeImage: "roleimages/stren.svg",
    popularPlace: "10th",
    popularPercent: "51.88%",
    stengthGain: "28+3.0",
    agilityGain: "17+1.7",
    itellegenceGain: "14+1.8",
    speed: 295,
    armor: 4.38,
    roles: "Melee, Carry, Disable, Durabler, Escape, Initiator",
  },
  {
    name: "Phantom Assasin",
    heroImage: "heroimages/phantom-assassin.jpg",
    heroType: "Agility Hero",
    typeImage: "roleimages/agill.svg",
    popularPlace: "10th",
    popularPercent: "51.88%",
    stengthGain: "28+3.0",
    agilityGain: "17+1.7",
    itellegenceGain: "14+1.8",
    speed: 295,
    armor: 4.38,
    roles: "Melee, Carry, Disable, Durabler, Escape, Initiator",
  },
  {
    name: "Storm Spirit",
    heroImage: "heroimages/storm-spirit.jpg",
    heroType: "Intellegence Hero",
    typeImage: "roleimages/intell.svg",
    popularPlace: "10th",
    popularPercent: "51.88%",
    stengthGain: "28+3.0",
    agilityGain: "17+1.7",
    itellegenceGain: "14+1.8",
    speed: 295,
    armor: 4.38,
    roles: "Melee, Carry, Disable, Durabler, Escape, Initiator",
  },

  {
    name: "Undying",
    heroImage: "heroimages/undying.jpg",
    heroType: "Strength Hero",
    typeImage: "roleimages/agill.svg",
    popularPlace: "10th",
    popularPercent: "51.88%",
    stengthGain: "28+3.0",
    agilityGain: "17+1.7",
    itellegenceGain: "14+1.8",
    speed: 295,
    armor: 4.38,
    roles: "Melee, Carry, Disable, Durabler, Escape, Initiator",
  },

  {
    name: "Rubick",
    heroImage: "heroimages/rubick.jpg",
    heroType: "Intellegence Hero",
    typeImage: "roleimages/intell.svg",
    popularPlace: "10th",
    popularPercent: "51.88%",
    stengthGain: "28+3.0",
    agilityGain: "17+1.7",
    itellegenceGain: "14+1.8",
    speed: 295,
    armor: 4.38,
    roles: "Melee, Carry, Disable, Durabler, Escape, Initiator",
  },

  {
    name: "Marci",
    heroImage: "heroimages/marci.jpg",
    heroType: "Strength Hero",
    typeImage: "roleimages/stren.svg",
    popularPlace: "10th",
    popularPercent: "51.88%",
    stengthGain: "28+3.0",
    agilityGain: "17+1.7",
    itellegenceGain: "14+1.8",
    speed: 295,
    armor: 4.38,
    roles: "Melee, Carry, Disable, Durabler, Escape, Initiator",
  },

  {
    name: "Grimstroke",
    heroImage: "heroimages/grimstroke.jpg",
    heroType: "Intellegence Hero",
    typeImage: "roleimages/intell.svg",
    popularPlace: "10th",
    popularPercent: "51.88%",
    stengthGain: "28+3.0",
    agilityGain: "17+1.7",
    itellegenceGain: "14+1.8",
    speed: 295,
    armor: 4.38,
    roles: "Melee, Carry, Disable, Durabler, Escape, Initiator",
  },

  {
    name: "Techies",
    heroImage: "heroimages/techies.jpg",
    heroType: "Intellegence Hero",
    typeImage: "roleimages/intell.svg",
    popularPlace: "10th",
    popularPercent: "51.88%",
    stengthGain: "28+3.0",
    agilityGain: "17+1.7",
    itellegenceGain: "14+1.8",
    speed: 295,
    armor: 4.38,
    roles: "Melee, Carry, Disable, Durabler, Escape, Initiator",
  },

  {
    name: "Pangolier",
    heroImage: "heroimages/pangolier.jpg",
    heroType: "Intellegence Hero",
    typeImage: "roleimages/intell.svg",
    popularPlace: "10th",
    popularPercent: "51.88%",
    stengthGain: "28+3.0",
    agilityGain: "17+1.7",
    itellegenceGain: "14+1.8",
    speed: 295,
    armor: 4.38,
    roles: "Melee, Carry, Disable, Durabler, Escape, Initiator",
  },

  {
    name: "Invoker",
    heroImage: "heroimages/invoker.jpg",
    heroType: "Intellegence Hero",
    typeImage: "roleimages/intell.svg",
    popularPlace: "10th",
    popularPercent: "51.88%",
    stengthGain: "28+3.0",
    agilityGain: "17+1.7",
    itellegenceGain: "14+1.8",
    speed: 295,
    armor: 4.38,
    roles: "Melee, Carry, Disable, Durabler, Escape, Initiator",
  },

  {
    name: "Lina",
    heroImage: "heroimages/lina.jpg",
    heroType: "Intellegence Hero",
    typeImage: "roleimages/intell.svg",
    popularPlace: "10th",
    popularPercent: "51.88%",
    stengthGain: "28+3.0",
    agilityGain: "17+1.7",
    itellegenceGain: "14+1.8",
    speed: 295,
    armor: 4.38,
    roles: "Melee, Carry, Disable, Durabler, Escape, Initiator",
  },
];
  